name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup Bun (for tauri-action which detects bun.lock)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.1.29"

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system deps (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Install deps (allow legacy peer deps)
        run: npm install --no-audit --no-fund --legacy-peer-deps

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Ensure base icon exists (optional)
        run: npm run icons:gen

      - name: Generate Tauri icons (.icns/.ico)
        run: npx @tauri-apps/cli icon src-tauri/icons/icon.png

      - name: Prepare Node sidecar binaries
        run: node ./scripts/prepare-node-sidecar.mjs

      - name: Determine Windows certificate presence
        if: matrix.platform == 'windows-latest'
        id: win_cert
        shell: pwsh
        run: |
          if ([string]::IsNullOrEmpty("${{ secrets.WINDOWS_CERTIFICATE_THUMBPRINT }}")) { echo "present=false" | Out-File -FilePath $env:GITHUB_OUTPUT -Append } else { echo "present=true" | Out-File -FilePath $env:GITHUB_OUTPUT -Append }

      - name: Disable Windows signing if certificate not provided
        if: matrix.platform == 'windows-latest' && steps.win_cert.outputs.present == 'false'
        shell: pwsh
        run: |
          $p = 'src-tauri/tauri.conf.json'
          $c = Get-Content $p -Raw
          $c = $c -replace '"certificateThumbprint":\s*"\$\{WINDOWS_CERTIFICATE_THUMBPRINT\}",\s*',''
          Set-Content $p -Value $c

      - name: Build Next.js standalone
        env:
          NEXT_TELEMETRY_DISABLED: "1"
        run: npm run build:tauri

      - name: Tauri build (no publish on non-tag)
        if: ${{ !startsWith(github.ref, 'refs/tags/') }}
        run: bun tauri build

      - name: Tauri build and publish (only on tag)
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: ${{ github.ref_name }}
          releaseName: Ganado AI ${{ github.ref_name }}
          releaseDraft: false
          prerelease: false
