name: Build Windows Desktop App (Tauri)

on:
  workflow_dispatch:
  push:
    branches:
      - feat/pwa-modules-ai

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        shell: bash
        run: bun install --frozen-lockfile

      - name: Setup Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build Tauri app (Windows)
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEXT_TELEMETRY_DISABLED: 1
          # Opcional: firma de Windows si está disponible
          WINDOWS_CERTIFICATE_THUMBPRINT: ${{ secrets.WINDOWS_CERTIFICATE_THUMBPRINT }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        with:
          projectPath: .
          tauriScript: bunx tauri

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-windows-dist
          path: |
            src-tauri/target/release/bundle/**
            src-tauri/target/release/*.exe
          if-no-files-found: warn


